#!/usr/bin/env python
# coding: utf-8

# # Configuration $(C_4)$

# In[1]:


load("basic_functions.sage")


# We define 6 points in a $(C_4)$ configuration. In the following block we study the ideal 
# $\delta_1(P_1, P_2, P_4), \delta_1(P_2, P_1, P_4), \delta_1(P_4, P_1, P_2)$ and we see
# it is, after admissible saturations, the ideal generated by $s_{12}, s_{14}, s_{24}$

# In[ ]:


P1 = vector(S, (A1, B1, C1))
P2 = vector(S, (A2, B2, C2))
P3 = u1*P1+u2*P2
P4 = vector(S, (A4, B4, C4))
P5 = v1*P1+v2*P4
P6 = w1*P2+w2*P4


# If we have configuration (4), then we must have:
# 
# $\delta_1(P_1, P_2, P_4) = 0$, $\delta_1(P_2, P_1, P_4) = 0$, $\delta_1(P_4, P_1, P_2) = 0$

# In[ ]:


J = S.ideal(delta1(P1, P2, P4), delta1(P2, P1, P4), delta1(P4, P1, P2))


# We saturate J w.r.t. some ideals which say that the points $P_1$, $P_2$, $P_4$ 
# do not have all the coordinates zero and $P_1$, $P_2$, $P_4$ are not aligned:

# In[ ]:


J = J.saturation(S.ideal(A1, B1, C1))[0]
J = J.saturation(S.ideal(A2, B2, C2))[0]
J = J.saturation(S.ideal(A4, B4, C4))[0]
J = J.saturation(S.ideal(matrix([P1, P2, P4]).det()))[0]


# Hence we have that 
# $J = \bigl( \left\langle P_1, P_2 \right\rangle, \left\langle P_1, P_4 \right\rangle, \left\langle P_2, P_4 \right\rangle \bigr)$

# In[ ]:


assert(
    J == 
    S.ideal(
        scalar_product(P1, P2),
        scalar_product(P1, P4),
        scalar_product(P2, P4)
    )
)


# The result is that the conditions defining $J$ imply that all 
# the possible $\delta_2$ are zero, so the points are in a (C8) configuration.

# In[3]:


assert(J.reduce(delta2(P1, P2, P3, P4, P5))==S.ideal(S(0)))
assert(J.reduce(delta2(P2, P1, P3, P4, P6))==S.ideal(S(0)))
assert(J.reduce(delta2(P4, P1, P5, P2, P6))==S.ideal(S(0)))


# CONCLUSION:
# 
# Configuration $(C_4)$ is not possible: it gives configuration $(C_8)$.
